/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.KaryawanController;
import controller.PelangganController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.PelangganModel;

/**
 *
 * @author Asrofin
 */
public class FrmUser extends javax.swing.JFrame {
private PelangganController control;
    private boolean status;
    private String proses;
    private List<PelangganModel> listPelanggan;
    private String[] tabelHeader;
    private DefaultTableModel dtm;
    private int row;
    /**
     * Creates new form FrmMain
     */
    public FrmUser() {
        initComponents();
        
        control = new PelangganController(this);
        lblKaryawan.setText(KaryawanController.getNamaKaryawan());

        proses = "";
        tabelHeader = new String[]{"Nama", "Telp", "Gender", "Alamat"};
        dtm = new DefaultTableModel(null, tabelHeader);
        tblPelanggan.setModel(dtm);
        tblPelanggan.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet.");
                row = tblPelanggan.getSelectedRow();
                if(row >= 0){
//                    txtNik.setText(dtm.getValueAt(row, 0).toString());
//                    txtNama.setText(dtm.getValueAt(row, 1).toString());
//                    txtTelp.setText(dtm.getValueAt(row, 2).toString());
//                    txtPassword.setText(dtm.getValueAt(row, 3).toString());
                }
            }
        });
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPelanggan = new javax.swing.JTable();
        lblKaryawan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTelp = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        rdbPerempuan = new javax.swing.JRadioButton();
        rdbLaki = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnUser.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1020, 776));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPelanggan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 510, 190));

        lblKaryawan.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblKaryawan.setText("Pekerja");
        jPanel1.add(lblKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 70, -1));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setText("Gender  :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setText("Nama     :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setText("Alamat  :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 70, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setText("Telp       :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));
        jPanel1.add(txtTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 150, 30));
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 150, 30));

        buttonGroup1.add(rdbPerempuan);
        rdbPerempuan.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        rdbPerempuan.setText("Perempuan");
        jPanel1.add(rdbPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        buttonGroup1.add(rdbLaki);
        rdbLaki.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        rdbLaki.setText("Laki-laki");
        jPanel1.add(rdbLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 180, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnBack.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setText("Pekerja :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 70, -1));

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnTambah.png"))); // NOI18N
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bguser.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        // TODO add your handling code here:
        String gender;
        if(rdbLaki.isSelected()){
            gender = "laki";
        }else if(rdbPerempuan.isSelected()){
            gender = "Perempuan";
        }else{
            gender = "";
        }
        
        String kosong = "";
        
        if(txtNama.getText().equals("") || 
                txtTelp.getText().equals("") ||
                txtAlamat.getText().equals("") || 
                gender.equals("")){
            JOptionPane.showMessageDialog(null, "Isi Data Terlebih Dahulu");
        }else{
        control.inputPelanggan(txtNama.getText(), txtTelp.getText(),
                           gender, txtAlamat.getText());
        //insert ke tabel staff
        boolean hasil = control.insertPelanggan();
        if(hasil == false){
            JOptionPane.showMessageDialog(null, "Penyimpanan gagal");
        }
        
        txtNama.setText("");
        txtTelp.setText("");
        txtAlamat.setText("");
        rdbLaki.setSelected(false);
        rdbPerempuan.setSelected(false);
        refreshTable();
        }
    }//GEN-LAST:event_btnTambahMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        FrmMain form2 = new FrmMain();
        form2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void refreshTable(){
        if(proses.equalsIgnoreCase("")){
           listPelanggan = control.selectPelanggan("");
        }

        dtm = (DefaultTableModel) tblPelanggan.getModel();
        dtm.setRowCount(0);
        for (PelangganModel data : listPelanggan){
            dtm.addRow(new Object[]{
                        data.getNama(),
                        data.getTelp(),
                        data.getGender(),
                        data.getAlamat()});
        }

        if(tblPelanggan.getRowCount() > 0){
            row = tblPelanggan.getRowCount() - 1;
            tblPelanggan.setRowSelectionInterval(row, row);
//            aturButton(true);
//            aturText(true);
            proses = "";
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnTambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblKaryawan;
    private javax.swing.JRadioButton rdbLaki;
    private javax.swing.JRadioButton rdbPerempuan;
    private javax.swing.JTable tblPelanggan;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables
}
